---
- name: Installation of the requirement in ALL NODES.
  hosts: nodes
  become: true
  vars:
   CONTAINERD_VERSION : "1.27"
  tasks:
#-------------------------- Install and configure containerd and docker--------------
    - name: Add signing key For Docker.
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present
    - name: Add repository into repo.d list.
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/centos/gpg"    
    - name: install containerd.
      yum:
        name: containerd
        state: present
    - name: add modprob modules.
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        create: yes
        block: |
          overlay
          br_netfilter
    - name: load modprobe overlay.
      community.general.modprobe:
        name: overlay
        state: present
    - name: load modprobe br_netfilter.
      community.general.modprobe:
        name: br_netfilter
        state: present
    - name: Writing in the created file.
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
    - name: Reload Configs without reboot.
      shell: sudo sysctl --system
    - name: set default config file for containerd.
      shell: sudo containerd config default > /etc/containerd/config.toml
    - name: start containerd.
      service:
        name: containerd
        state: started
        enabled: true
#####-----------Disable Swapp----------######################################
    - name: Disable Swapp.
      shell: |
        swapoff -a
    - name : Check disable SWAP in fstab.
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
#------------------Install Required Packages-----------------------------------#
    - name: Install Required Packages.
      yum:
        name:
          - git
          - wget
          - curl
          - ca-certificates
          - iptables
#------------------Add Kubernetes Repo And kubeadm init------------------------#
    - name: add Kubernetes Repo.
      yum_repository:
        name: kubernetes
        description: Kubernetes YUM Repository
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        state: present
    - name: Disable SELinux.
      shell : sudo setenforce 0
    - name: Set SELinux in permissive mode (effectively disabling it).
      command: sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    - name: apply sysctl params without reboot
      shell: sysctl --system
    - name: Install Kubeadm Kubelet Kubectl All Nodes.
      yum:
        name:
          - kubectl-1.27.6
          - kubeadm-1.27.6
          - kubelet-1.27.6
    - name: Enable kubelet
      service:
        name: kubelet
        enabled: yes
        state: started
    - name: Add hosts to hosts file.
      blockinfile:
        path: /etc/hosts
        state: present
        block: |
          10.112.100.60 master
          10.112.100.61 worker1
          10.112.100.62 worker2