---
- name: Register to Red Hat Devolope.
  hosts: nodes
  gather_facts: no
  become: true
  vars_prompt:
    - name: "password"
      prompt: "Enter the password"
      private: yes
  tasks:
    - name: Register with username and password.
      community.general.redhat_subscription:
        state: present
        username: "ismail.bouaziz@onetech-group.com"
        password: "{{ password }}" 
    - name: Subscribe to a specific pool by ID.
      community.general.redhat_subscription:
        state: present
        username: "ismail.bouaziz@onetech-group.com"
        password: "{{ password }}" 
        pool_ids: 2c94594c8a3cf97d018a45c163205c52
    - name: Update Red Hat Entreprise Linux.
      ansible.builtin.shell: dnf update -y